// Autogenerated from Pigeon (v26.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Generated.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray<id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static FlutterError *createConnectionError(NSString *channelName) {
  return [FlutterError errorWithCode:@"channel-error" message:[NSString stringWithFormat:@"%@/%@/%@", @"Unable to establish connection on channel: '", channelName, @"'."] details:@""];
}

static id GetNullableObjectAtIndex(NSArray<id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@implementation WTPHandleTypeEnumBox
- (instancetype)initWithValue:(WTPHandleTypeEnum)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation WTPCallInfoConstsBox
- (instancetype)initWithValue:(WTPCallInfoConsts)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation WTPEndCallReasonEnumBox
- (instancetype)initWithValue:(WTPEndCallReasonEnum)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation WTPIncomingCallErrorEnumBox
- (instancetype)initWithValue:(WTPIncomingCallErrorEnum)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@implementation WTPCallRequestErrorEnumBox
- (instancetype)initWithValue:(WTPCallRequestErrorEnum)value {
  self = [super init];
  if (self) {
    _value = value;
  }
  return self;
}
@end

@interface WTPIOSOptions ()
+ (WTPIOSOptions *)fromList:(NSArray<id> *)list;
+ (nullable WTPIOSOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface WTPAndroidOptions ()
+ (WTPAndroidOptions *)fromList:(NSArray<id> *)list;
+ (nullable WTPAndroidOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface WTPOptions ()
+ (WTPOptions *)fromList:(NSArray<id> *)list;
+ (nullable WTPOptions *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface WTPHandle ()
+ (WTPHandle *)fromList:(NSArray<id> *)list;
+ (nullable WTPHandle *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface WTPEndCallReason ()
+ (WTPEndCallReason *)fromList:(NSArray<id> *)list;
+ (nullable WTPEndCallReason *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface WTPIncomingCallError ()
+ (WTPIncomingCallError *)fromList:(NSArray<id> *)list;
+ (nullable WTPIncomingCallError *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@interface WTPCallRequestError ()
+ (WTPCallRequestError *)fromList:(NSArray<id> *)list;
+ (nullable WTPCallRequestError *)nullableFromList:(NSArray<id> *)list;
- (NSArray<id> *)toList;
@end

@implementation WTPIOSOptions
+ (instancetype)makeWithLocalizedName:(NSString *)localizedName
    ringtoneSound:(nullable NSString *)ringtoneSound
    ringbackSound:(nullable NSString *)ringbackSound
    iconTemplateImageAssetName:(nullable NSString *)iconTemplateImageAssetName
    maximumCallGroups:(NSInteger )maximumCallGroups
    maximumCallsPerCallGroup:(NSInteger )maximumCallsPerCallGroup
    supportsHandleTypeGeneric:(nullable NSNumber *)supportsHandleTypeGeneric
    supportsHandleTypePhoneNumber:(nullable NSNumber *)supportsHandleTypePhoneNumber
    supportsHandleTypeEmailAddress:(nullable NSNumber *)supportsHandleTypeEmailAddress
    supportsVideo:(BOOL )supportsVideo
    includesCallsInRecents:(BOOL )includesCallsInRecents
    driveIdleTimerDisabled:(BOOL )driveIdleTimerDisabled {
  WTPIOSOptions* pigeonResult = [[WTPIOSOptions alloc] init];
  pigeonResult.localizedName = localizedName;
  pigeonResult.ringtoneSound = ringtoneSound;
  pigeonResult.ringbackSound = ringbackSound;
  pigeonResult.iconTemplateImageAssetName = iconTemplateImageAssetName;
  pigeonResult.maximumCallGroups = maximumCallGroups;
  pigeonResult.maximumCallsPerCallGroup = maximumCallsPerCallGroup;
  pigeonResult.supportsHandleTypeGeneric = supportsHandleTypeGeneric;
  pigeonResult.supportsHandleTypePhoneNumber = supportsHandleTypePhoneNumber;
  pigeonResult.supportsHandleTypeEmailAddress = supportsHandleTypeEmailAddress;
  pigeonResult.supportsVideo = supportsVideo;
  pigeonResult.includesCallsInRecents = includesCallsInRecents;
  pigeonResult.driveIdleTimerDisabled = driveIdleTimerDisabled;
  return pigeonResult;
}
+ (WTPIOSOptions *)fromList:(NSArray<id> *)list {
  WTPIOSOptions *pigeonResult = [[WTPIOSOptions alloc] init];
  pigeonResult.localizedName = GetNullableObjectAtIndex(list, 0);
  pigeonResult.ringtoneSound = GetNullableObjectAtIndex(list, 1);
  pigeonResult.ringbackSound = GetNullableObjectAtIndex(list, 2);
  pigeonResult.iconTemplateImageAssetName = GetNullableObjectAtIndex(list, 3);
  pigeonResult.maximumCallGroups = [GetNullableObjectAtIndex(list, 4) integerValue];
  pigeonResult.maximumCallsPerCallGroup = [GetNullableObjectAtIndex(list, 5) integerValue];
  pigeonResult.supportsHandleTypeGeneric = GetNullableObjectAtIndex(list, 6);
  pigeonResult.supportsHandleTypePhoneNumber = GetNullableObjectAtIndex(list, 7);
  pigeonResult.supportsHandleTypeEmailAddress = GetNullableObjectAtIndex(list, 8);
  pigeonResult.supportsVideo = [GetNullableObjectAtIndex(list, 9) boolValue];
  pigeonResult.includesCallsInRecents = [GetNullableObjectAtIndex(list, 10) boolValue];
  pigeonResult.driveIdleTimerDisabled = [GetNullableObjectAtIndex(list, 11) boolValue];
  return pigeonResult;
}
+ (nullable WTPIOSOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WTPIOSOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.localizedName ?: [NSNull null],
    self.ringtoneSound ?: [NSNull null],
    self.ringbackSound ?: [NSNull null],
    self.iconTemplateImageAssetName ?: [NSNull null],
    @(self.maximumCallGroups),
    @(self.maximumCallsPerCallGroup),
    self.supportsHandleTypeGeneric ?: [NSNull null],
    self.supportsHandleTypePhoneNumber ?: [NSNull null],
    self.supportsHandleTypeEmailAddress ?: [NSNull null],
    @(self.supportsVideo),
    @(self.includesCallsInRecents),
    @(self.driveIdleTimerDisabled),
  ];
}
@end

@implementation WTPAndroidOptions
+ (instancetype)makeWithRingtoneSound:(nullable NSString *)ringtoneSound
    ringbackSound:(nullable NSString *)ringbackSound {
  WTPAndroidOptions* pigeonResult = [[WTPAndroidOptions alloc] init];
  pigeonResult.ringtoneSound = ringtoneSound;
  pigeonResult.ringbackSound = ringbackSound;
  return pigeonResult;
}
+ (WTPAndroidOptions *)fromList:(NSArray<id> *)list {
  WTPAndroidOptions *pigeonResult = [[WTPAndroidOptions alloc] init];
  pigeonResult.ringtoneSound = GetNullableObjectAtIndex(list, 0);
  pigeonResult.ringbackSound = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable WTPAndroidOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WTPAndroidOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.ringtoneSound ?: [NSNull null],
    self.ringbackSound ?: [NSNull null],
  ];
}
@end

@implementation WTPOptions
+ (instancetype)makeWithIos:(WTPIOSOptions *)ios
    android:(WTPAndroidOptions *)android {
  WTPOptions* pigeonResult = [[WTPOptions alloc] init];
  pigeonResult.ios = ios;
  pigeonResult.android = android;
  return pigeonResult;
}
+ (WTPOptions *)fromList:(NSArray<id> *)list {
  WTPOptions *pigeonResult = [[WTPOptions alloc] init];
  pigeonResult.ios = GetNullableObjectAtIndex(list, 0);
  pigeonResult.android = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable WTPOptions *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WTPOptions fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    self.ios ?: [NSNull null],
    self.android ?: [NSNull null],
  ];
}
@end

@implementation WTPHandle
+ (instancetype)makeWithType:(WTPHandleTypeEnum)type
    value:(NSString *)value {
  WTPHandle* pigeonResult = [[WTPHandle alloc] init];
  pigeonResult.type = type;
  pigeonResult.value = value;
  return pigeonResult;
}
+ (WTPHandle *)fromList:(NSArray<id> *)list {
  WTPHandle *pigeonResult = [[WTPHandle alloc] init];
  WTPHandleTypeEnumBox *boxedWTPHandleTypeEnum = GetNullableObjectAtIndex(list, 0);
  pigeonResult.type = boxedWTPHandleTypeEnum.value;
  pigeonResult.value = GetNullableObjectAtIndex(list, 1);
  return pigeonResult;
}
+ (nullable WTPHandle *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WTPHandle fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[WTPHandleTypeEnumBox alloc] initWithValue:self.type],
    self.value ?: [NSNull null],
  ];
}
@end

@implementation WTPEndCallReason
+ (instancetype)makeWithValue:(WTPEndCallReasonEnum)value {
  WTPEndCallReason* pigeonResult = [[WTPEndCallReason alloc] init];
  pigeonResult.value = value;
  return pigeonResult;
}
+ (WTPEndCallReason *)fromList:(NSArray<id> *)list {
  WTPEndCallReason *pigeonResult = [[WTPEndCallReason alloc] init];
  WTPEndCallReasonEnumBox *boxedWTPEndCallReasonEnum = GetNullableObjectAtIndex(list, 0);
  pigeonResult.value = boxedWTPEndCallReasonEnum.value;
  return pigeonResult;
}
+ (nullable WTPEndCallReason *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WTPEndCallReason fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[WTPEndCallReasonEnumBox alloc] initWithValue:self.value],
  ];
}
@end

@implementation WTPIncomingCallError
+ (instancetype)makeWithValue:(WTPIncomingCallErrorEnum)value {
  WTPIncomingCallError* pigeonResult = [[WTPIncomingCallError alloc] init];
  pigeonResult.value = value;
  return pigeonResult;
}
+ (WTPIncomingCallError *)fromList:(NSArray<id> *)list {
  WTPIncomingCallError *pigeonResult = [[WTPIncomingCallError alloc] init];
  WTPIncomingCallErrorEnumBox *boxedWTPIncomingCallErrorEnum = GetNullableObjectAtIndex(list, 0);
  pigeonResult.value = boxedWTPIncomingCallErrorEnum.value;
  return pigeonResult;
}
+ (nullable WTPIncomingCallError *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WTPIncomingCallError fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[WTPIncomingCallErrorEnumBox alloc] initWithValue:self.value],
  ];
}
@end

@implementation WTPCallRequestError
+ (instancetype)makeWithValue:(WTPCallRequestErrorEnum)value {
  WTPCallRequestError* pigeonResult = [[WTPCallRequestError alloc] init];
  pigeonResult.value = value;
  return pigeonResult;
}
+ (WTPCallRequestError *)fromList:(NSArray<id> *)list {
  WTPCallRequestError *pigeonResult = [[WTPCallRequestError alloc] init];
  WTPCallRequestErrorEnumBox *boxedWTPCallRequestErrorEnum = GetNullableObjectAtIndex(list, 0);
  pigeonResult.value = boxedWTPCallRequestErrorEnum.value;
  return pigeonResult;
}
+ (nullable WTPCallRequestError *)nullableFromList:(NSArray<id> *)list {
  return (list) ? [WTPCallRequestError fromList:list] : nil;
}
- (NSArray<id> *)toList {
  return @[
    [[WTPCallRequestErrorEnumBox alloc] initWithValue:self.value],
  ];
}
@end

@interface WTGeneratedPigeonCodecReader : FlutterStandardReader
@end
@implementation WTGeneratedPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
  switch (type) {
    case 129: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[WTPHandleTypeEnumBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 130: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[WTPCallInfoConstsBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 131: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[WTPEndCallReasonEnumBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 132: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[WTPIncomingCallErrorEnumBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 133: {
      NSNumber *enumAsNumber = [self readValue];
      return enumAsNumber == nil ? nil : [[WTPCallRequestErrorEnumBox alloc] initWithValue:[enumAsNumber integerValue]];
    }
    case 134: 
      return [WTPIOSOptions fromList:[self readValue]];
    case 135: 
      return [WTPAndroidOptions fromList:[self readValue]];
    case 136: 
      return [WTPOptions fromList:[self readValue]];
    case 137: 
      return [WTPHandle fromList:[self readValue]];
    case 138: 
      return [WTPEndCallReason fromList:[self readValue]];
    case 139: 
      return [WTPIncomingCallError fromList:[self readValue]];
    case 140: 
      return [WTPCallRequestError fromList:[self readValue]];
    default:
      return [super readValueOfType:type];
  }
}
@end

@interface WTGeneratedPigeonCodecWriter : FlutterStandardWriter
@end
@implementation WTGeneratedPigeonCodecWriter
- (void)writeValue:(id)value {
  if ([value isKindOfClass:[WTPHandleTypeEnumBox class]]) {
    WTPHandleTypeEnumBox *box = (WTPHandleTypeEnumBox *)value;
    [self writeByte:129];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[WTPCallInfoConstsBox class]]) {
    WTPCallInfoConstsBox *box = (WTPCallInfoConstsBox *)value;
    [self writeByte:130];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[WTPEndCallReasonEnumBox class]]) {
    WTPEndCallReasonEnumBox *box = (WTPEndCallReasonEnumBox *)value;
    [self writeByte:131];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[WTPIncomingCallErrorEnumBox class]]) {
    WTPIncomingCallErrorEnumBox *box = (WTPIncomingCallErrorEnumBox *)value;
    [self writeByte:132];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[WTPCallRequestErrorEnumBox class]]) {
    WTPCallRequestErrorEnumBox *box = (WTPCallRequestErrorEnumBox *)value;
    [self writeByte:133];
    [self writeValue:(value == nil ? [NSNull null] : [NSNumber numberWithInteger:box.value])];
  } else if ([value isKindOfClass:[WTPIOSOptions class]]) {
    [self writeByte:134];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[WTPAndroidOptions class]]) {
    [self writeByte:135];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[WTPOptions class]]) {
    [self writeByte:136];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[WTPHandle class]]) {
    [self writeByte:137];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[WTPEndCallReason class]]) {
    [self writeByte:138];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[WTPIncomingCallError class]]) {
    [self writeByte:139];
    [self writeValue:[value toList]];
  } else if ([value isKindOfClass:[WTPCallRequestError class]]) {
    [self writeByte:140];
    [self writeValue:[value toList]];
  } else {
    [super writeValue:value];
  }
}
@end

@interface WTGeneratedPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation WTGeneratedPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[WTGeneratedPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[WTGeneratedPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *WTGetGeneratedCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
  static dispatch_once_t sPred = 0;
  dispatch_once(&sPred, ^{
    WTGeneratedPigeonCodecReaderWriter *readerWriter = [[WTGeneratedPigeonCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}
void SetUpWTPHostAndroidServiceApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostAndroidServiceApi> *api) {
  SetUpWTPHostAndroidServiceApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpWTPHostAndroidServiceApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostAndroidServiceApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostAndroidServiceApi.hungUp", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(hungUpCallId:uuidString:completion:)], @"WTPHostAndroidServiceApi api (%@) doesn't respond to @selector(hungUpCallId:uuidString:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_callId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 1);
        [api hungUpCallId:arg_callId uuidString:arg_uuidString completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostAndroidServiceApi.incomingCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(incomingCallCallId:uuidString:handle:displayName:hasVideo:completion:)], @"WTPHostAndroidServiceApi api (%@) doesn't respond to @selector(incomingCallCallId:uuidString:handle:displayName:hasVideo:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_callId = GetNullableObjectAtIndex(args, 0);
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 1);
        WTPHandle *arg_handle = GetNullableObjectAtIndex(args, 2);
        NSString *arg_displayName = GetNullableObjectAtIndex(args, 3);
        BOOL arg_hasVideo = [GetNullableObjectAtIndex(args, 4) boolValue];
        [api incomingCallCallId:arg_callId uuidString:arg_uuidString handle:arg_handle displayName:arg_displayName hasVideo:arg_hasVideo completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
void SetUpWTPHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostApi> *api) {
  SetUpWTPHostApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpWTPHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.isSetUp", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isSetUp:)], @"WTPHostApi api (%@) doesn't respond to @selector(isSetUp:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSNumber *output = [api isSetUp:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.setUp", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setUp:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(setUp:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        WTPOptions *arg_options = GetNullableObjectAtIndex(args, 0);
        [api setUp:arg_options completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.tearDown", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(tearDown:)], @"WTPHostApi api (%@) doesn't respond to @selector(tearDown:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api tearDown:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.reportNewIncomingCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportNewIncomingCall:handle:displayName:hasVideo:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(reportNewIncomingCall:handle:displayName:hasVideo:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        WTPHandle *arg_handle = GetNullableObjectAtIndex(args, 1);
        NSString *arg_displayName = GetNullableObjectAtIndex(args, 2);
        BOOL arg_hasVideo = [GetNullableObjectAtIndex(args, 3) boolValue];
        [api reportNewIncomingCall:arg_uuidString handle:arg_handle displayName:arg_displayName hasVideo:arg_hasVideo completion:^(WTPIncomingCallError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.reportConnectingOutgoingCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportConnectingOutgoingCall:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(reportConnectingOutgoingCall:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        [api reportConnectingOutgoingCall:arg_uuidString completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.reportConnectedOutgoingCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportConnectedOutgoingCall:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(reportConnectedOutgoingCall:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        [api reportConnectedOutgoingCall:arg_uuidString completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.reportUpdateCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportUpdateCall:handle:displayName:hasVideo:proximityEnabled:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(reportUpdateCall:handle:displayName:hasVideo:proximityEnabled:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        WTPHandle *arg_handle = GetNullableObjectAtIndex(args, 1);
        NSString *arg_displayName = GetNullableObjectAtIndex(args, 2);
        NSNumber *arg_hasVideo = GetNullableObjectAtIndex(args, 3);
        NSNumber *arg_proximityEnabled = GetNullableObjectAtIndex(args, 4);
        [api reportUpdateCall:arg_uuidString handle:arg_handle displayName:arg_displayName hasVideo:arg_hasVideo proximityEnabled:arg_proximityEnabled completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.reportEndCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(reportEndCall:displayName:reason:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(reportEndCall:displayName:reason:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        NSString *arg_displayName = GetNullableObjectAtIndex(args, 1);
        WTPEndCallReason *arg_reason = GetNullableObjectAtIndex(args, 2);
        [api reportEndCall:arg_uuidString displayName:arg_displayName reason:arg_reason completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.startCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(startCall:handle:displayNameOrContactIdentifier:video:proximityEnabled:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(startCall:handle:displayNameOrContactIdentifier:video:proximityEnabled:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        WTPHandle *arg_handle = GetNullableObjectAtIndex(args, 1);
        NSString *arg_displayNameOrContactIdentifier = GetNullableObjectAtIndex(args, 2);
        BOOL arg_video = [GetNullableObjectAtIndex(args, 3) boolValue];
        BOOL arg_proximityEnabled = [GetNullableObjectAtIndex(args, 4) boolValue];
        [api startCall:arg_uuidString handle:arg_handle displayNameOrContactIdentifier:arg_displayNameOrContactIdentifier video:arg_video proximityEnabled:arg_proximityEnabled completion:^(WTPCallRequestError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.answerCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(answerCall:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(answerCall:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        [api answerCall:arg_uuidString completion:^(WTPCallRequestError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.endCall", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(endCall:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(endCall:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        [api endCall:arg_uuidString completion:^(WTPCallRequestError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.setHeld", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setHeld:onHold:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(setHeld:onHold:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        BOOL arg_onHold = [GetNullableObjectAtIndex(args, 1) boolValue];
        [api setHeld:arg_uuidString onHold:arg_onHold completion:^(WTPCallRequestError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.setMuted", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setMuted:muted:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(setMuted:muted:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        BOOL arg_muted = [GetNullableObjectAtIndex(args, 1) boolValue];
        [api setMuted:arg_uuidString muted:arg_muted completion:^(WTPCallRequestError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.setSpeaker", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(setSpeaker:enabled:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(setSpeaker:enabled:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        BOOL arg_enabled = [GetNullableObjectAtIndex(args, 1) boolValue];
        [api setSpeaker:arg_uuidString enabled:arg_enabled completion:^(WTPCallRequestError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostApi.sendDTMF", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(sendDTMF:key:completion:)], @"WTPHostApi api (%@) doesn't respond to @selector(sendDTMF:key:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_uuidString = GetNullableObjectAtIndex(args, 0);
        NSString *arg_key = GetNullableObjectAtIndex(args, 1);
        [api sendDTMF:arg_uuidString key:arg_key completion:^(WTPCallRequestError *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface WTPDelegateFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation WTPDelegateFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)continueStartCallIntentHandle:(WTPHandle *)arg_handle displayName:(nullable NSString *)arg_displayName video:(BOOL)arg_video completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.continueStartCallIntent", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_handle ?: [NSNull null], arg_displayName ?: [NSNull null], @(arg_video)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)didPushIncomingCallHandle:(WTPHandle *)arg_handle displayName:(nullable NSString *)arg_displayName video:(BOOL)arg_video callId:(NSString *)arg_callId uuid:(NSString *)arg_uuidString error:(nullable WTPIncomingCallError *)arg_error completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.didPushIncomingCall", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_handle ?: [NSNull null], arg_displayName ?: [NSNull null], @(arg_video), arg_callId ?: [NSNull null], arg_uuidString ?: [NSNull null], arg_error ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)performStartCall:(NSString *)arg_uuidString handle:(WTPHandle *)arg_handle displayNameOrContactIdentifier:(nullable NSString *)arg_displayNameOrContactIdentifier video:(BOOL)arg_video completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.performStartCall", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_uuidString ?: [NSNull null], arg_handle ?: [NSNull null], arg_displayNameOrContactIdentifier ?: [NSNull null], @(arg_video)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
- (void)performAnswerCall:(NSString *)arg_uuidString completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.performAnswerCall", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_uuidString ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
- (void)performEndCall:(NSString *)arg_uuidString completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.performEndCall", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_uuidString ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
- (void)performSetHeld:(NSString *)arg_uuidString onHold:(BOOL)arg_onHold completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.performSetHeld", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_uuidString ?: [NSNull null], @(arg_onHold)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
- (void)performSetMuted:(NSString *)arg_uuidString muted:(BOOL)arg_muted completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.performSetMuted", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_uuidString ?: [NSNull null], @(arg_muted)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
- (void)performSetSpeaker:(NSString *)arg_uuidString enabled:(BOOL)arg_enabled completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.performSetSpeaker", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_uuidString ?: [NSNull null], @(arg_enabled)] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
- (void)performSendDTMF:(NSString *)arg_uuidString key:(NSString *)arg_key completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.performSendDTMF", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_uuidString ?: [NSNull null], arg_key ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion(nil, [FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        NSNumber *output = reply[0] == [NSNull null] ? nil : reply[0];
        completion(output, nil);
      }
    } else {
      completion(nil, createConnectionError(channelName));
    } 
  }];
}
- (void)didActivateAudioSession:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.didActivateAudioSession", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)didDeactivateAudioSession:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.didDeactivateAudioSession", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
- (void)didReset:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateFlutterApi.didReset", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:nil reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

@interface WTPDelegateAndroidServiceFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation WTPDelegateAndroidServiceFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)performEndCallUuidString:(NSString *)arg_uuidString completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PDelegateAndroidServiceFlutterApi.performEndCall", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_uuidString ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

void SetUpWTPPushRegistryHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPPushRegistryHostApi> *api) {
  SetUpWTPPushRegistryHostApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpWTPPushRegistryHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPPushRegistryHostApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PPushRegistryHostApi.pushTokenForPushTypeVoIP", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(pushTokenForPushTypeVoIP:)], @"WTPPushRegistryHostApi api (%@) doesn't respond to @selector(pushTokenForPushTypeVoIP:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        NSString *output = [api pushTokenForPushTypeVoIP:&error];
        callback(wrapResult(output, error));
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
@interface WTPPushRegistryDelegateFlutterApi ()
@property(nonatomic, strong) NSObject<FlutterBinaryMessenger> *binaryMessenger;
@property(nonatomic, strong) NSString *messageChannelSuffix;
@end

@implementation WTPPushRegistryDelegateFlutterApi

- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger {
  return [self initWithBinaryMessenger:binaryMessenger messageChannelSuffix:@""];
}
- (instancetype)initWithBinaryMessenger:(NSObject<FlutterBinaryMessenger> *)binaryMessenger messageChannelSuffix:(nullable NSString*)messageChannelSuffix{
  self = [self init];
  if (self) {
    _binaryMessenger = binaryMessenger;
    _messageChannelSuffix = [messageChannelSuffix length] == 0 ? @"" : [NSString stringWithFormat: @".%@", messageChannelSuffix];
  }
  return self;
}
- (void)didUpdatePushTokenForPushTypeVoIP:(nullable NSString *)arg_token completion:(void (^)(FlutterError *_Nullable))completion {
  NSString *channelName = [NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PPushRegistryDelegateFlutterApi.didUpdatePushTokenForPushTypeVoIP", _messageChannelSuffix];
  FlutterBasicMessageChannel *channel =
    [FlutterBasicMessageChannel
      messageChannelWithName:channelName
      binaryMessenger:self.binaryMessenger
      codec:WTGetGeneratedCodec()];
  [channel sendMessage:@[arg_token ?: [NSNull null]] reply:^(NSArray<id> *reply) {
    if (reply != nil) {
      if (reply.count > 1) {
        completion([FlutterError errorWithCode:reply[0] message:reply[1] details:reply[2]]);
      } else {
        completion(nil);
      }
    } else {
      completion(createConnectionError(channelName));
    } 
  }];
}
@end

void SetUpWTAndroidHelperHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTAndroidHelperHostApi> *api) {
  SetUpWTAndroidHelperHostApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpWTAndroidHelperHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTAndroidHelperHostApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.AndroidHelperHostApi.wakeUpApp", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(wakeUpAppPath:completion:)], @"WTAndroidHelperHostApi api (%@) doesn't respond to @selector(wakeUpAppPath:completion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        NSArray<id> *args = message;
        NSString *arg_path = GetNullableObjectAtIndex(args, 0);
        [api wakeUpAppPath:arg_path completion:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.AndroidHelperHostApi.isLockScreen", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(isLockScreenWithCompletion:)], @"WTAndroidHelperHostApi api (%@) doesn't respond to @selector(isLockScreenWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api isLockScreenWithCompletion:^(NSNumber *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
void SetUpWTPHostSoundApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostSoundApi> *api) {
  SetUpWTPHostSoundApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpWTPHostSoundApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostSoundApi> *api, NSString *messageChannelSuffix) {
  messageChannelSuffix = messageChannelSuffix.length > 0 ? [NSString stringWithFormat: @".%@", messageChannelSuffix] : @"";
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostSoundApi.playRingbackSound", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(playRingbackSound:)], @"WTPHostSoundApi api (%@) doesn't respond to @selector(playRingbackSound:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api playRingbackSound:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.webtrit_callkeep_ios.PHostSoundApi.stopRingbackSound", messageChannelSuffix]
        binaryMessenger:binaryMessenger
        codec:WTGetGeneratedCodec()];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(stopRingbackSound:)], @"WTPHostSoundApi api (%@) doesn't respond to @selector(stopRingbackSound:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api stopRingbackSound:^(FlutterError *_Nullable error) {
          callback(wrapResult(nil, error));
        }];
      }];
    } else {
      [channel setMessageHandler:nil];
    }
  }
}
