// Autogenerated from Pigeon (v26.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

typedef NS_ENUM(NSUInteger, WTPHandleTypeEnum) {
  WTPHandleTypeEnumGeneric = 0,
  WTPHandleTypeEnumNumber = 1,
  WTPHandleTypeEnumEmail = 2,
};

/// Wrapper for WTPHandleTypeEnum to allow for nullability.
@interface WTPHandleTypeEnumBox : NSObject
@property(nonatomic, assign) WTPHandleTypeEnum value;
- (instancetype)initWithValue:(WTPHandleTypeEnum)value;
@end

typedef NS_ENUM(NSUInteger, WTPCallInfoConsts) {
  WTPCallInfoConstsUuid = 0,
  WTPCallInfoConstsDtmf = 1,
  WTPCallInfoConstsIsVideo = 2,
  WTPCallInfoConstsNumber = 3,
  WTPCallInfoConstsName = 4,
};

/// Wrapper for WTPCallInfoConsts to allow for nullability.
@interface WTPCallInfoConstsBox : NSObject
@property(nonatomic, assign) WTPCallInfoConsts value;
- (instancetype)initWithValue:(WTPCallInfoConsts)value;
@end

typedef NS_ENUM(NSUInteger, WTPEndCallReasonEnum) {
  WTPEndCallReasonEnumFailed = 0,
  WTPEndCallReasonEnumRemoteEnded = 1,
  WTPEndCallReasonEnumUnanswered = 2,
  WTPEndCallReasonEnumAnsweredElsewhere = 3,
  WTPEndCallReasonEnumDeclinedElsewhere = 4,
  WTPEndCallReasonEnumMissed = 5,
};

/// Wrapper for WTPEndCallReasonEnum to allow for nullability.
@interface WTPEndCallReasonEnumBox : NSObject
@property(nonatomic, assign) WTPEndCallReasonEnum value;
- (instancetype)initWithValue:(WTPEndCallReasonEnum)value;
@end

typedef NS_ENUM(NSUInteger, WTPIncomingCallErrorEnum) {
  WTPIncomingCallErrorEnumUnknown = 0,
  WTPIncomingCallErrorEnumUnentitled = 1,
  WTPIncomingCallErrorEnumCallUuidAlreadyExists = 2,
  WTPIncomingCallErrorEnumFilteredByDoNotDisturb = 3,
  WTPIncomingCallErrorEnumFilteredByBlockList = 4,
  WTPIncomingCallErrorEnumInternal = 5,
};

/// Wrapper for WTPIncomingCallErrorEnum to allow for nullability.
@interface WTPIncomingCallErrorEnumBox : NSObject
@property(nonatomic, assign) WTPIncomingCallErrorEnum value;
- (instancetype)initWithValue:(WTPIncomingCallErrorEnum)value;
@end

typedef NS_ENUM(NSUInteger, WTPCallRequestErrorEnum) {
  WTPCallRequestErrorEnumUnknown = 0,
  WTPCallRequestErrorEnumUnentitled = 1,
  WTPCallRequestErrorEnumUnknownCallUuid = 2,
  WTPCallRequestErrorEnumCallUuidAlreadyExists = 3,
  WTPCallRequestErrorEnumMaximumCallGroupsReached = 4,
  WTPCallRequestErrorEnumInternal = 5,
};

/// Wrapper for WTPCallRequestErrorEnum to allow for nullability.
@interface WTPCallRequestErrorEnumBox : NSObject
@property(nonatomic, assign) WTPCallRequestErrorEnum value;
- (instancetype)initWithValue:(WTPCallRequestErrorEnum)value;
@end

@class WTPIOSOptions;
@class WTPAndroidOptions;
@class WTPOptions;
@class WTPHandle;
@class WTPEndCallReason;
@class WTPIncomingCallError;
@class WTPCallRequestError;

@interface WTPIOSOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithLocalizedName:(NSString *)localizedName
    ringtoneSound:(nullable NSString *)ringtoneSound
    ringbackSound:(nullable NSString *)ringbackSound
    iconTemplateImageAssetName:(nullable NSString *)iconTemplateImageAssetName
    maximumCallGroups:(NSInteger )maximumCallGroups
    maximumCallsPerCallGroup:(NSInteger )maximumCallsPerCallGroup
    supportsHandleTypeGeneric:(nullable NSNumber *)supportsHandleTypeGeneric
    supportsHandleTypePhoneNumber:(nullable NSNumber *)supportsHandleTypePhoneNumber
    supportsHandleTypeEmailAddress:(nullable NSNumber *)supportsHandleTypeEmailAddress
    supportsVideo:(BOOL )supportsVideo
    includesCallsInRecents:(BOOL )includesCallsInRecents
    driveIdleTimerDisabled:(BOOL )driveIdleTimerDisabled;
@property(nonatomic, copy) NSString * localizedName;
@property(nonatomic, copy, nullable) NSString * ringtoneSound;
@property(nonatomic, copy, nullable) NSString * ringbackSound;
@property(nonatomic, copy, nullable) NSString * iconTemplateImageAssetName;
@property(nonatomic, assign) NSInteger  maximumCallGroups;
@property(nonatomic, assign) NSInteger  maximumCallsPerCallGroup;
@property(nonatomic, strong, nullable) NSNumber * supportsHandleTypeGeneric;
@property(nonatomic, strong, nullable) NSNumber * supportsHandleTypePhoneNumber;
@property(nonatomic, strong, nullable) NSNumber * supportsHandleTypeEmailAddress;
@property(nonatomic, assign) BOOL  supportsVideo;
@property(nonatomic, assign) BOOL  includesCallsInRecents;
@property(nonatomic, assign) BOOL  driveIdleTimerDisabled;
@end

@interface WTPAndroidOptions : NSObject
+ (instancetype)makeWithRingtoneSound:(nullable NSString *)ringtoneSound
    ringbackSound:(nullable NSString *)ringbackSound;
@property(nonatomic, copy, nullable) NSString * ringtoneSound;
@property(nonatomic, copy, nullable) NSString * ringbackSound;
@end

@interface WTPOptions : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithIos:(WTPIOSOptions *)ios
    android:(WTPAndroidOptions *)android;
@property(nonatomic, strong) WTPIOSOptions * ios;
@property(nonatomic, strong) WTPAndroidOptions * android;
@end

@interface WTPHandle : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithType:(WTPHandleTypeEnum)type
    value:(NSString *)value;
@property(nonatomic, assign) WTPHandleTypeEnum type;
@property(nonatomic, copy) NSString * value;
@end

@interface WTPEndCallReason : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithValue:(WTPEndCallReasonEnum)value;
@property(nonatomic, assign) WTPEndCallReasonEnum value;
@end

@interface WTPIncomingCallError : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithValue:(WTPIncomingCallErrorEnum)value;
@property(nonatomic, assign) WTPIncomingCallErrorEnum value;
@end

@interface WTPCallRequestError : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithValue:(WTPCallRequestErrorEnum)value;
@property(nonatomic, assign) WTPCallRequestErrorEnum value;
@end

/// The codec used by all APIs.
NSObject<FlutterMessageCodec> *WTGetGeneratedCodec(void);

@protocol WTPHostAndroidServiceApi
- (void)hungUpCallId:(NSString *)callId uuidString:(NSString *)uuidString completion:(void (^)(FlutterError *_Nullable))completion;
- (void)incomingCallCallId:(NSString *)callId uuidString:(NSString *)uuidString handle:(WTPHandle *)handle displayName:(nullable NSString *)displayName hasVideo:(BOOL)hasVideo completion:(void (^)(FlutterError *_Nullable))completion;
@end

extern void SetUpWTPHostAndroidServiceApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostAndroidServiceApi> *_Nullable api);

extern void SetUpWTPHostAndroidServiceApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostAndroidServiceApi> *_Nullable api, NSString *messageChannelSuffix);


@protocol WTPHostApi
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)isSetUp:(FlutterError *_Nullable *_Nonnull)error;
- (void)setUp:(WTPOptions *)options completion:(void (^)(FlutterError *_Nullable))completion;
- (void)tearDown:(void (^)(FlutterError *_Nullable))completion;
- (void)reportNewIncomingCall:(NSString *)uuidString handle:(WTPHandle *)handle displayName:(nullable NSString *)displayName hasVideo:(BOOL)hasVideo completion:(void (^)(WTPIncomingCallError *_Nullable, FlutterError *_Nullable))completion;
- (void)reportConnectingOutgoingCall:(NSString *)uuidString completion:(void (^)(FlutterError *_Nullable))completion;
- (void)reportConnectedOutgoingCall:(NSString *)uuidString completion:(void (^)(FlutterError *_Nullable))completion;
- (void)reportUpdateCall:(NSString *)uuidString handle:(nullable WTPHandle *)handle displayName:(nullable NSString *)displayName hasVideo:(nullable NSNumber *)hasVideo proximityEnabled:(nullable NSNumber *)proximityEnabled completion:(void (^)(FlutterError *_Nullable))completion;
- (void)reportEndCall:(NSString *)uuidString displayName:(NSString *)displayName reason:(WTPEndCallReason *)reason completion:(void (^)(FlutterError *_Nullable))completion;
- (void)startCall:(NSString *)uuidString handle:(WTPHandle *)handle displayNameOrContactIdentifier:(nullable NSString *)displayNameOrContactIdentifier video:(BOOL)video proximityEnabled:(BOOL)proximityEnabled completion:(void (^)(WTPCallRequestError *_Nullable, FlutterError *_Nullable))completion;
- (void)answerCall:(NSString *)uuidString completion:(void (^)(WTPCallRequestError *_Nullable, FlutterError *_Nullable))completion;
- (void)endCall:(NSString *)uuidString completion:(void (^)(WTPCallRequestError *_Nullable, FlutterError *_Nullable))completion;
- (void)setHeld:(NSString *)uuidString onHold:(BOOL)onHold completion:(void (^)(WTPCallRequestError *_Nullable, FlutterError *_Nullable))completion;
- (void)setMuted:(NSString *)uuidString muted:(BOOL)muted completion:(void (^)(WTPCallRequestError *_Nullable, FlutterError *_Nullable))completion;
- (void)setSpeaker:(NSString *)uuidString enabled:(BOOL)enabled completion:(void (^)(WTPCallRequestError *_Nullable, FlutterError *_Nullable))completion;
- (void)sendDTMF:(NSString *)uuidString key:(NSString *)key completion:(void (^)(WTPCallRequestError *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpWTPHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostApi> *_Nullable api);

extern void SetUpWTPHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostApi> *_Nullable api, NSString *messageChannelSuffix);


@interface WTPDelegateFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)continueStartCallIntentHandle:(WTPHandle *)handle displayName:(nullable NSString *)displayName video:(BOOL)video completion:(void (^)(FlutterError *_Nullable))completion;
- (void)didPushIncomingCallHandle:(WTPHandle *)handle displayName:(nullable NSString *)displayName video:(BOOL)video callId:(NSString *)callId uuid:(NSString *)uuidString error:(nullable WTPIncomingCallError *)error completion:(void (^)(FlutterError *_Nullable))completion;
- (void)performStartCall:(NSString *)uuidString handle:(WTPHandle *)handle displayNameOrContactIdentifier:(nullable NSString *)displayNameOrContactIdentifier video:(BOOL)video completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)performAnswerCall:(NSString *)uuidString completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)performEndCall:(NSString *)uuidString completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)performSetHeld:(NSString *)uuidString onHold:(BOOL)onHold completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)performSetMuted:(NSString *)uuidString muted:(BOOL)muted completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)performSetSpeaker:(NSString *)uuidString enabled:(BOOL)enabled completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)performSendDTMF:(NSString *)uuidString key:(NSString *)key completion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
- (void)didActivateAudioSession:(void (^)(FlutterError *_Nullable))completion;
- (void)didDeactivateAudioSession:(void (^)(FlutterError *_Nullable))completion;
- (void)didReset:(void (^)(FlutterError *_Nullable))completion;
@end


@interface WTPDelegateAndroidServiceFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)performEndCallUuidString:(NSString *)uuidString completion:(void (^)(FlutterError *_Nullable))completion;
@end


@protocol WTPPushRegistryHostApi
- (nullable NSString *)pushTokenForPushTypeVoIP:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void SetUpWTPPushRegistryHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPPushRegistryHostApi> *_Nullable api);

extern void SetUpWTPPushRegistryHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPPushRegistryHostApi> *_Nullable api, NSString *messageChannelSuffix);


@interface WTPPushRegistryDelegateFlutterApi : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger messageChannelSuffix:(nullable NSString *)messageChannelSuffix;
- (void)didUpdatePushTokenForPushTypeVoIP:(nullable NSString *)token completion:(void (^)(FlutterError *_Nullable))completion;
@end


@protocol WTAndroidHelperHostApi
- (void)wakeUpAppPath:(nullable NSString *)path completion:(void (^)(FlutterError *_Nullable))completion;
- (void)isLockScreenWithCompletion:(void (^)(NSNumber *_Nullable, FlutterError *_Nullable))completion;
@end

extern void SetUpWTAndroidHelperHostApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTAndroidHelperHostApi> *_Nullable api);

extern void SetUpWTAndroidHelperHostApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTAndroidHelperHostApi> *_Nullable api, NSString *messageChannelSuffix);


@protocol WTPHostSoundApi
- (void)playRingbackSound:(void (^)(FlutterError *_Nullable))completion;
- (void)stopRingbackSound:(void (^)(FlutterError *_Nullable))completion;
@end

extern void SetUpWTPHostSoundApi(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostSoundApi> *_Nullable api);

extern void SetUpWTPHostSoundApiWithSuffix(id<FlutterBinaryMessenger> binaryMessenger, NSObject<WTPHostSoundApi> *_Nullable api, NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
