include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    lines_longer_than_80_chars: false # Conflicts with the team's preference
    # public_member_api_docs: false
    one_member_abstracts: false # TODO: on migration stage
    avoid_positional_boolean_parameters: # TODO: on migration stage

formatter:
  page_width: 120
